version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pg_admin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: akhileshmahajan3107@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
    volumes:
       - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5433:80"
    networks:
      - postgres
    restart: unless-stopped
  
volumes:
    postgres-data:
    pgadmin-data:

networks:
  postgres:
    driver: bridge